			<div id="footer">
				<div class="footer-content">
					<p>
					影JOY 2011. <br/ ><strong>資料來源: </strong>&nbsp;&nbsp;
					<a href="http://www.truemovie.com/" title="Truemovie">觸電網</a> &nbsp;|&nbsp;
					<a href="http://tw.movie.yahoo.com/" title="YahooMovies">Yahoo! 電影</a> &nbsp;|&nbsp;
					<a href="http://www.atmovies.com.tw/home/" title="Atmovies">開眼電影網</a> &nbsp;|&nbsp;
					</p>
				</div>
			</div>