    <div id="nav">
    	<ul>
            <li><a href="logout.do">登出</a></li>
			<li><a href="memberInfoPage.jsp">個人資訊</a></li>
            <li><a href="release_date.jsp">上映檔期</a></li>
			<li>
				<a href="#">電影院資訊</a>		
				<ul>
					<li><a href="movieShowTime.jsp">查詢場次</a></li>
					<li><a href="route_map.jsp">電影院搜尋</a></li>
				</ul>			
			</li>
			<li><a href="comments.jsp">電影評論</a></li>
			<li><a href="whichMovie.jsp">Which Movie</a></li>
			<li><a href="wizard.do">電影資訊精靈</a></li>
			<li><a href="channelList.jsp">電影節目表</a></li>
        </ul>
    </div>