<!--
				<div class="sidebar">
					<fieldset>
					<legend>會員登入</legend>
					<form method="post">
						<p>
							<label>帳號:</label>
							<input type="text" size="10" value="" name="username" class="s" />
							<input name="sign" style="margin-left: 5px; float:right;" class="formbutton" value="加入會員" type="submit" />
							<br />
							<label>密碼:</label>
							<input type="password" size="10" value="" name="password" class="s" />
							<input name="login" style="margin-left: 5px; float:right;" class="formbutton" value="會員登入" type="submit" />
						</p>
					</form>
					</fieldset>
					
					<fieldset>
						<legend>近期電影票選</legend>
						<form method="post">
							<p>
								<label for="movie1">享受吧!一個人的旅行</label>
								<input name="vote" value="A" type="radio" /><br />
								<label for="movie2">華爾街2</label>
								<input name="vote" value="B" type="radio" /><br />
								<label for="movie3">竊盜城</label>
								<input name="vote" value="C" type="radio" /><br />
								<label for="movie4">惡靈古堡4: 陰陽界</label>
								<input name="vote" value="D" type="radio" /><br />
								<label for="movie5">叛獄風雲</label>
								<input name="vote" value="E" type="radio" /><br />
								<input name="send" style="margin-left: 5px; float:right;" class="formbutton" value="投票" type="submit" />
							</p>
						</form>
					</fieldset>
				</div>
				<div class="clear"></div>
-->